-- 여수 등대 스탬프 투어 익명 설문 저장 테이블
-- Supabase Dashboard > SQL Editor에서 전체 실행하세요.
-- 방문자에게는 INSERT만 허용하고 SELECT / UPDATE / DELETE는 허용하지 않습니다.

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  survey_version text not null
    check (char_length(survey_version) between 1 and 30),
  language text not null
    check (language in ('ko', 'en', 'ja', 'zh')),
  overall_satisfaction smallint not null
    check (overall_satisfaction between 1 and 5),
  participation_clarity smallint not null
    check (participation_clarity between 1 and 5),
  stamp_process_convenience smallint not null
    check (stamp_process_convenience between 1 and 5),
  operation_satisfaction text not null
    check (operation_satisfaction in ('1', '2', '3', '4', '5', 'not_used')),
  lighthouse_interest smallint
    check (lighthouse_interest is null or lighthouse_interest between 1 and 5),
  future_participation smallint
    check (future_participation is null or future_participation between 1 and 5),
  inconveniences text[] not null default '{}',
  improvement_comment text not null default ''
    check (char_length(improvement_comment) <= 1000),
  positive_comment text not null default ''
    check (char_length(positive_comment) <= 1000),
  submitted_at_client timestamptz,
  source_page text not null default 'survey.html'
    check (char_length(source_page) between 1 and 100),
  constraint survey_responses_inconveniences_allowed check (
    inconveniences <@ array[
      'method', 'location', 'route', 'stamp', 'qr',
      'guidance', 'gift', 'other', 'none'
    ]::text[]
    and cardinality(inconveniences) <= 9
    and not ('none' = any(inconveniences) and cardinality(inconveniences) > 1)
  )
);

comment on table public.survey_responses is
  '이름·전화번호·이메일을 받지 않는 여수 등대 스탬프 투어 만족도 설문 응답';

alter table public.survey_responses enable row level security;

-- 기존 공개 권한을 제거하고 필요한 INSERT 권한만 최소 부여합니다.
revoke all on table public.survey_responses from public, anon, authenticated;
grant insert on table public.survey_responses to anon;

-- identity 기본값(nextval)을 사용하기 위한 최소 권한입니다.
revoke all on sequence public.survey_responses_id_seq from public, anon, authenticated;
grant usage on sequence public.survey_responses_id_seq to anon;

-- 재실행해도 정책이 중복되지 않도록 기존 정책을 교체합니다.
drop policy if exists "Anonymous visitors can submit survey responses" on public.survey_responses;
create policy "Anonymous visitors can submit survey responses"
on public.survey_responses
for insert
to anon
with check (true);

-- SELECT / UPDATE / DELETE 정책은 만들지 않습니다.
-- 따라서 Publishable key를 사용하는 일반 방문자는 응답을 읽거나 수정·삭제할 수 없습니다.
